import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarUI from '@/app/components/Navigation'
import type { Footer, Navbar, NavbarBundle } from '@/app/types/types'
import { client } from "@/sanity/client";
import { FOOTER_QUERY } from "@/sanity/queries";
import FooterComponent from "./components/footer";
import AuthProvider from "./components/providers/SessionProvider";
//import Footer from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const  NAVBAR_QUERY =`{
  "navbar": *[_type == "navbar"][0]{
    _id, title, logo,
    items[]{
      _key, label, type, openInNewTab,
      links[]{
        label,
        externalUrl,
        slug,
        internalReference->{
          _type, _id,
          "slug": slug.current
        }
      }
    }
  },
  "pages": *[_type == "page"]{ _id, title, "slug": slug.current },
  "posts": *[_type == "post"]{ _id, title, "slug": slug.current }
}

`;

const navbarData = await client.fetch<NavbarBundle>(NAVBAR_QUERY, {}, { next: { revalidate: 60 } })

const footerData = await client.fetch<{ footer: Footer }>(FOOTER_QUERY);
//const footerData =  await client.fetch<Footer>(FOOTER_QUERY , {}, { next: { revalidate: 60 } })
    console.log('footerData ' , footerData)
  return (
    <html lang="en">
      <body   className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen `}>

            
       <AuthProvider>
         {navbarData?.navbar && (
          <NavbarUI
            navbar={navbarData.navbar}
            pages={navbarData.pages}
            posts={navbarData.posts}
          />
        )}

      
          {children}
        </AuthProvider>
        
    <FooterComponent data={ footerData.footer}/>
      </body>
    </html>
  );
}
